# Basic Python
## 3. NumPy Arrays

NumPy arrays, or `ndarray`, are a popular structure in Python that enable the storage of data in multi-dimensional matrices. While they share similarities with Python Lists, they are distinguished by the fact that they can only contain **elements of the same data type**. This characteristic optimizes the memory layout and results in more efficient computation, making `ndarray` an ideal data structure for handling images and large datasets.  

NumPy `ndarray` are used by a multitude of scientific Python libraries, including SciPy, Scikit-learn, Pandas and Matplotlib, making them a fundamental data structure to learn.  

Add:
- oriented for number computing
- similar to matlab
- it comes with NumPy package wich contains many functions
- ndarray have a lot of associated methods and attributes

<hr style="border-top: 1px">

To use `ndarray`, you will first need to install the NumPy package and import it as follow:  
Learn more about installing Python packages [here](https://packaging.python.org/en/latest/tutorials/installing-packages/). 

In [2]:
import numpy
import numpy as np # using np alias

`ndarray` are created from lists or tuples using the `np.array()` function.

In [5]:
my_array_from_list = np.array([1, 2, 3, 4, 5]) # list (default)
my_array_from_tuple = np.array((1, 2, 3, 4, 5)) # tuple
print(my_array_from_list)
print(my_array_from_tuple)

[1 2 3 4 5]
[1 2 3 4 5]


<hr style="border-top: 1px">

`ndarray` can be **multi-dimensional**, ranging from 0 to n dimension.  
`ndarray` are **indexed** and individual elements can be retrieved as with Python lists and tuples. 

In [19]:
# 0-D array or scalar
my_array_0D = np.array(1)
print(my_array_0D)

1


For **1D arrays**, the index refers t

In [21]:
# 1-D array or vector
my_array_1D = np.array([1, 2])
print(my_array_1D)
print(my_array_1D[1]) # 2nd element

[1 2]
2


For **2D arrays**, the first index refers to rows and the second to columns.

In [22]:
# 2-D array or matrix
my_array_2D = np.array([[1, 2], [3, 4]])
print(my_array_2D)
print(my_array_2D[1][0]) # 2nd row of 1st column (2D array)
print(my_array_2D[0][1]) # 1st row of 2nd column (2D array)

[[1 2]
 [3 4]]
3
2


For **3D arrays**, the first index refers to 2D array, the second to rows and the third to columns.

In [24]:
# 3-D array or matrix
my_array_3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(my_array_3D)
print(my_array_3D[0][1][0]) # 2nd row, 1st column of 1st 2D array (3D array)
print(my_array_3D[1][0][1]) # 1st row, 2nd column of 2nd 2D array (3D array)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
6


<hr style="border-top: 1px">

In [13]:
print(my_array_2D[1, 0]) # 2nd row, 1st column (2D array)
print(my_array_3D[0, 1, 0]) # 2nd row, 1st column, 1st 2D array (3D array)
print(my_array_2D[0,...]) # all elements of 2nd row (2D array)
print(my_array_3D[1,...]) # all elements of 2nd 2D array (3D array)

3
3
[1 2]
[[5 6]
 [7 8]]
