# Basic Python
## 3. NumPy Arrays

NumPy arrays, or `ndarray`, are a popular structure in Python that enable the storage of data in multi-dimensional matrices. While they share similarities with Python Lists, they are distinguished by the fact that they can only contain **elements of the same data type**. This characteristic optimizes the memory layout and results in more efficient computation, making `ndarray` an ideal data structure for handling images and large datasets.  

NumPy `ndarray` are used by a multitude of scientific Python libraries, including SciPy, Scikit-learn, Pandas and Matplotlib, making them a fundamental data structure to learn.  

Add:
- oriented for number computing
- similar to matlab
- it comes with NumPy package wich contains many functions
- ndarray have a lot of associated methods and attributes

<hr style="border-top: 1px">

To use `ndarray`, you will first need to install the NumPy package and import it as follow:  
Learn more about installing Python packages [here](https://packaging.python.org/en/latest/tutorials/installing-packages/). 

In [4]:
import numpy
import numpy as np # using np alias

`ndarray` are created from lists or tuples using the `np.array()` function.

In [5]:
my_array_from_list = np.array([1, 2, 3, 4, 5]) # list (default)
my_array_from_tuple = np.array((1, 2, 3, 4, 5)) # tuple
print(my_array_from_list)
print(my_array_from_tuple)

[1 2 3 4 5]
[1 2 3 4 5]


<hr style="border-top: 1px">

`ndarray` can be **multi-dimensional**, ranging from 0 to n dimension.

In [32]:
# 0-D array or scalar
my_array_0D = np.array(1)
# 1-D array or vector
my_array_1D = np.array([1, 2])
# 2-D array or matrix
my_array_2D = np.array([[1, 2], [3, 4]])
# 3-D array or matrix
my_array_3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(my_array_3D)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


<hr style="border-top: 1px">

`ndarray` are **indexed** and individual elements can be retrieved as with Python lists and tuples.  

In [45]:
# 1-D array or vector
print(my_array_1D[0]) # first element (1D array)
print(my_array_1D[-1]) # last element of a 1D array
# 2-D array or matrix
print(my_array_2D[1][0]) # 2nd row, 1st column (2D array)
print(my_array_2D[0][1]) # 1st row, 2nd column (2D array)
# 3-D array or matrix
print(my_array_3D[0][1][0]) # 2nd row, 1st column, 1st 2D array (3D array)
print(my_array_3D[1][1][0]) # 2nd row, 1st column, 2nd 2D array (3D array)

1
2
3
2
4
8


In [ ]:
print(my_array_2D[1, 0]) # 2nd row, 1st column (2D array)
print(my_array_3D[0, 1, 0]) # 2nd row, 1st column, 1st 2D array (3D array)